import type { TopicSignal } from './types';

function generateSparkline(baseScore: number, points = 24): { timestamp: number; score: number }[] {
  const now = Date.now();
  return Array.from({ length: points }, (_, i) => ({
    timestamp: now - (points - i) * 3600000,
    score: Math.max(0, Math.min(100, baseScore + (Math.random() - 0.5) * 30 + Math.sin(i / 4) * 10)),
  }));
}

export const mockTopics: TopicSignal[] = [
  {
    id: 'eth',
    name: 'Ethereum',
    ticker: 'ETH',
    category: 'Blockchain',
    score: 68,
    label: 'Greed',
    change24h: 3.2,
    change7d: 11.5,
    volume: 8420000000,
    narrativeStrength: 82,
    dominantNarrative: 'Institutional accumulation accelerates post-ETF approval signals',
    signals: { bullish: 147, bearish: 42, neutral: 63 },
    sparkline: generateSparkline(68),
    lastUpdated: new Date(Date.now() - 180000).toISOString(),
    transmissionId: 'TRX-0041-ETH',
  },
  {
    id: 'btc',
    name: 'Bitcoin',
    ticker: 'BTC',
    category: 'Coin',
    score: 82,
    label: 'Extreme Greed',
    change24h: 1.8,
    change7d: 17.3,
    volume: 31200000000,
    narrativeStrength: 94,
    dominantNarrative: 'Halving cycle momentum sustains record inflows via spot ETFs',
    signals: { bullish: 312, bearish: 28, neutral: 41 },
    sparkline: generateSparkline(82),
    lastUpdated: new Date(Date.now() - 90000).toISOString(),
    transmissionId: 'TRX-0039-BTC',
  },
  {
    id: 'uni',
    name: 'Uniswap',
    ticker: 'UNI',
    category: 'Protocol',
    score: 44,
    label: 'Fear',
    change24h: -2.1,
    change7d: -6.4,
    volume: 420000000,
    narrativeStrength: 58,
    dominantNarrative: 'Regulatory overhang suppresses governance token sentiment',
    signals: { bullish: 64, bearish: 91, neutral: 47 },
    sparkline: generateSparkline(44),
    lastUpdated: new Date(Date.now() - 420000).toISOString(),
    transmissionId: 'TRX-0044-UNI',
  },
  {
    id: 'sol',
    name: 'Solana',
    ticker: 'SOL',
    category: 'Blockchain',
    score: 74,
    label: 'Greed',
    change24h: 5.6,
    change7d: 22.1,
    volume: 3800000000,
    narrativeStrength: 77,
    dominantNarrative: 'DePIN ecosystem expansion drives developer migration narrative',
    signals: { bullish: 204, bearish: 38, neutral: 59 },
    sparkline: generateSparkline(74),
    lastUpdated: new Date(Date.now() - 240000).toISOString(),
    transmissionId: 'TRX-0042-SOL',
  },
  {
    id: 'arb',
    name: 'Arbitrum',
    ticker: 'ARB',
    category: 'Blockchain',
    score: 38,
    label: 'Fear',
    change24h: -4.3,
    change7d: -12.8,
    volume: 280000000,
    narrativeStrength: 49,
    dominantNarrative: 'L2 competition intensifies amid token unlock schedule concerns',
    signals: { bullish: 52, bearish: 118, neutral: 71 },
    sparkline: generateSparkline(38),
    lastUpdated: new Date(Date.now() - 600000).toISOString(),
    transmissionId: 'TRX-0047-ARB',
  },
  {
    id: 'aave',
    name: 'Aave',
    ticker: 'AAVE',
    category: 'Protocol',
    score: 55,
    label: 'Neutral',
    change24h: 0.4,
    change7d: 3.2,
    volume: 190000000,
    narrativeStrength: 61,
    dominantNarrative: 'V4 roadmap and GHO stablecoin traction stabilize sentiment',
    signals: { bullish: 88, bearish: 72, neutral: 94 },
    sparkline: generateSparkline(55),
    lastUpdated: new Date(Date.now() - 360000).toISOString(),
    transmissionId: 'TRX-0045-AAVE',
  },
  {
    id: 'link',
    name: 'Chainlink',
    ticker: 'LINK',
    category: 'Protocol',
    score: 61,
    label: 'Greed',
    change24h: 2.7,
    change7d: 8.9,
    volume: 520000000,
    narrativeStrength: 69,
    dominantNarrative: 'CCIP cross-chain adoption by TradFi institutions gains traction',
    signals: { bullish: 121, bearish: 54, neutral: 68 },
    sparkline: generateSparkline(61),
    lastUpdated: new Date(Date.now() - 150000).toISOString(),
    transmissionId: 'TRX-0043-LINK',
  },
  {
    id: 'avax',
    name: 'Avalanche',
    ticker: 'AVAX',
    category: 'Blockchain',
    score: 22,
    label: 'Extreme Fear',
    change24h: -7.8,
    change7d: -19.4,
    volume: 610000000,
    narrativeStrength: 35,
    dominantNarrative: 'Subnet adoption stalls amid competitive pressure from newer L1s',
    signals: { bullish: 31, bearish: 187, neutral: 44 },
    sparkline: generateSparkline(22),
    lastUpdated: new Date(Date.now() - 720000).toISOString(),
    transmissionId: 'TRX-0048-AVAX',
  },
  {
    id: 'mkr',
    name: 'MakerDAO',
    ticker: 'MKR',
    category: 'Protocol',
    score: 49,
    label: 'Neutral',
    change24h: -0.9,
    change7d: 1.4,
    volume: 95000000,
    narrativeStrength: 55,
    dominantNarrative: 'Endgame rebranding to Sky protocol divides community sentiment',
    signals: { bullish: 77, bearish: 81, neutral: 102 },
    sparkline: generateSparkline(49),
    lastUpdated: new Date(Date.now() - 480000).toISOString(),
    transmissionId: 'TRX-0046-MKR',
  },
  {
    id: 'op',
    name: 'Optimism',
    ticker: 'OP',
    category: 'Blockchain',
    score: 57,
    label: 'Neutral',
    change24h: 1.2,
    change7d: 4.8,
    volume: 310000000,
    narrativeStrength: 63,
    dominantNarrative: 'Superchain architecture attracts Coinbase Base and new OP Stack chains',
    signals: { bullish: 94, bearish: 67, neutral: 88 },
    sparkline: generateSparkline(57),
    lastUpdated: new Date(Date.now() - 300000).toISOString(),
    transmissionId: 'TRX-0040-OP',
  },
];

export const systemStatus = {
  totalTransmissions: 2847,
  activeMonitors: 10,
  lastSweep: new Date(Date.now() - 90000).toISOString(),
  networkHealth: 98.4,
  tickerItems: [
    'BTC SIGNAL: EXTREME GREED — HALVING CYCLE MOMENTUM',
    'ETH SIGNAL: INSTITUTIONAL FLOW DETECTED',
    'SOL SIGNAL: DEPIN NARRATIVE DOMINANCE',
    'SYSTEM: NARRATIVE SWEEP COMPLETE — 2847 TRANSMISSIONS PROCESSED',
    'LINK SIGNAL: TRADFI CCIP ADOPTION CONFIRMED',
    'AVAX SIGNAL: EXTREME FEAR — CAPITULATION WATCH',
    'ARB SIGNAL: L2 COMPETITION PRESSURE ELEVATED',
  ],
};
